image:
  file: .devcontainer/Dockerfile

tasks:
  - init: dotnet restore
  - command: dotnet test

vscode:
  extensions:
    - ms-dotnettools.csharp
    - tintoy.msbuild-project-tools
    - formulahendry.dotnet-test-explorer
    - nikiforovall.surround-with-csharp
    - mhutchie.git-graph
    - codezombiech.gitignore
    - yzhang.markdown-all-in-one
    - dotjoshjohnson.xml
    - editorconfig.editorconfig
    - leo-labs.dotnet
    - fernandoescolar.vscode-solution-explorer
    - cschleiden.vscode-github-action

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true